# Generated by Django 3.2.3 on 2021-05-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductValues',
            new_name='ProductMinValue',
        ),
    ]
