# Generated by Django 3.2.3 on 2021-05-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
