# Generated by Django 3.2.3 on 2021-07-08 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210525_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='productminvalue',
            options={'verbose_name': 'Preço Minimo', 'verbose_name_plural': 'Preços Minimos'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='company',
            name='web_site',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productminvalue',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=300, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='', verbose_name='Url da imagem'),
        ),
        migrations.AlterField(
            model_name='productminvalue',
            name='min_value',
            field=models.FloatField(verbose_name='Valor Minimo'),
        ),
        migrations.AlterField(
            model_name='productminvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product', verbose_name='Produto'),
        ),
        migrations.CreateModel(
            name='WebSiteDivElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_div', models.CharField(max_length=400, verbose_name='Class Preço')),
                ('ame_div', models.CharField(max_length=400, verbose_name='Class Ame')),
                ('description_div', models.CharField(max_length=400, verbose_name='Class Descrição')),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='pages.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Elemento Site',
                'verbose_name_plural': 'Elementos Site',
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.product')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preços',
            },
        ),
    ]
