# Generated by Django 3.2.3 on 2021-07-08 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210707_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
